swagger: "2.0"
info:
  version: "1.0.0"
  title: "Dwarrowdelf"
host: "localhost:8080"
basePath: "/"
tags:
  - name: "status"
    description: ""
  - name: "greeting"
    description: ""
  - name: "account"
    description: ""
schemes:
  - "http"
paths:
  /status:
    get:
      tags:
        - "status"
      summary: ""
      description: ""
      operationId: "getStatus"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/BaseResponse"
          examples:
            application/json:
              {
                "dateTime": "2020-09-30T13:05:28.128",
                "message": "UP!",
              }
  /greeting:
    post:
      tags:
        - "greeting"
      summary: ""
      description: ""
      operationId: "sayHello"
      parameters:
        - in: "body"
          name: "User"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/UserRequest"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/BaseResponse"
          examples:
            application/json:
              {
                "dateTime": "2020-09-30T13:05:20.708",
                "message": "Hello John Wick"
              }
  /account:
    get:
      tags:
        - "account"
      summary: ""
      description: ""
      operationId: "findAccount"
      parameters:
        - in: query
          name: no
          type: integer
          required: true
          default: 80001
          description: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: ""
          schema:
            $ref: "#/definitions/BaseResponse"
          examples:
            application/json:
              {
                "dateTime": "2020-09-30T13:23:12.885",
                "message": "[ no=80002, balance=20000 ]"
              }
        "404":
          description: ""
          schema:
            $ref: "#/definitions/BaseResponse"
          examples:
            application/json:
              {
                "dateTime": "2020-09-30T13:25:45.122",
                "message": "Account number 800023 not found"
              }
definitions:
  UserRequest:
    type: object
    properties:
      name:
        type: string
        example: "John Wick"
  BaseResponse:
    type: object
    properties:
      dateTime:
        type: string
      message:
        type: string